---
name: Scan Container

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  scan-container:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
      security-events: write
    uses: ministryofjustice/analytical-platform-airflow-github-actions/.github/workflows/shared-grype-scan.yml@e25799aec7782bc6bf01a56ca60329a31c2bf125
    with:
      runtime: python
